name: Build with vcpkg

on:
  push:
    branches:
      - master
      - v*

    tags:
      - v*

    paths:
      - cmake/**
      - src/**
      - inc/**
      - test/**
      - CMakeLists.txt

  pull_request:
    paths:
      - cmake/**
      - src/**
      - inc/**
      - test/**
      - CMakeLists.txt

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, macos-clang, windows-msvc]
        buildtype: [Debug, Release]
        luajit: [on, off]
        include:
          - name: windows-msvc
            os: windows
            cxx: cl.exe
            cc: cl.exe
            triplet: x64-windows
            packages: >
              libsqlite
          - name: ubuntu-gcc
            os: ubuntu
            cxx: g++
            cc: gcc
            triplet: x64-linux
            packages: >
              libsqlite
          - name: ubuntu-clang
            os: ubuntu
            cxx: clang++
            cc: clang
            triplet: x64-linux
            packages: >
              libsqlite
          - name: macos-clang
            os: macos
            cxx: clang++
            cc: clang
            triplet: x64-osx
            packages: >
              libsqlite

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get latest CMake
        # Using 'latest' branch, the latest CMake is installed.
        uses: lukka/get-cmake@latest

      - uses: lukka/set-shell-env@v1
        with:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}

      - name: Build with CMake
        uses: lukka/run-cmake@v2
        with:
          useVcpkgToolchainFile: true
          buildDirectory: ${{ runner.workspace }}/build
          cmakeBuildType: ${{ matrix.buildtype }}

      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Upload artifact binary
        uses: actions/upload-artifact@v2
        with:
          name: tfs-${{ matrix.name }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
        if: "! contains( matrix.os, 'windows')"

      - name: Upload artifact binary (exe)
        uses: actions/upload-artifact@v2
        with:
          name: tfs-${{ matrix.name }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs.exe
        if: contains( matrix.os, 'windows')

      - name: Upload artifact binary (dlls)
        uses: actions/upload-artifact@v2
        with:
          name: tfs-${{ matrix.name }}-${{ matrix.buildtype }}-luajit=${{ matrix.luajit }}-${{ github.sha }}
          path: ${{ runner.workspace }}/build/*.dll
        if: contains( matrix.os, 'windows')

